name: Functions

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/functions.yml'
      - 'functions/**'
      - 'scripts/*'
      - 'scripts/functions.sh'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/functions.yml'
      - 'functions/**'
      - 'scripts/*'
      - 'scripts/functions.sh'

  workflow_dispatch:

env:
  SAMPLE: Functions
  secrets_passphrase: ${{ secrets.GHASECRETSGPGPASSPHRASE1 }}

jobs:
  cocoapods:
    name: cocoapods
    runs-on: macOS-latest
    env:
      SPM: false
      LEGACY: true
      OS: iOS
      DEVICE: iPhone 11
      TEST: true
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd functions/LegacyFunctionsQuickstart
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
          cd ..
          ../scripts/install_prereqs/functions.sh
      - name: Build ObjC
        run: ./scripts/test.sh
        env:
          SWIFT_SUFFIX: ""
      - name: Build Swift
        run: ./scripts/test.sh
        env:
          SWIFT_SUFFIX: Swift

  spm:
    name: spm 
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ["13.0"]
        os: [iOS]
        include:
          - os: iOS
            device: iPhone 11
            test: false
    env:
      SETUP: functions
      SPM: true
      DIR: functions/FunctionsExample/
      OS: ${{ matrix.os }}
      DEVICE: ${{ matrix.device }}
      TEST: ${{ matrix.test }}
      XCODE_VERSION: ${{ matrix.xcode }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          sudo xcode-select -s "/Applications/Xcode_${XCODE_VERSION}.app/Contents/Developer"
          gem install xcpretty
          cd $SETUP
          ../scripts/install_prereqs/${SETUP}.sh
      - name: Build and Test SwiftUI (${{ matrix.os }})
        run: ./scripts/test.sh
